arguments:
  parameters:
    - name: repository
      value: "morzhanov/atlas-playground"
    - name: branch
      value: "main"
    - name: filepath
      value: "emailtree/installation-file.yaml"
    - name: deploy-argocd-version
      value: v2.0.5
    - name: deploy-revision
      value: main
    - name: deploy-flags
      value: --
