metadata:
  generateName: delay-
  namespace: argo
  labels:
    clusterName: hubcluster
spec:
  entrypoint: starter
  arguments:
    parameters:
      - name: message
        value: "Test message!"
  templates:
    - name: starter
      steps:
        - - name: delay
            templateRef:
              name: delay
              template: delay
            arguments:
              parameters:
                - name: message
                  value: "{{workflow.parameters.message}}"
