apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: example-workflow
spec:
  entrypoint: whalesay
  arguments:
    parameters:
      - name: message
        value: hello world
      - name: cmvalue
        valueFrom:
          configMapKeyRef:
            name: simple-parameters
            key: message
  templates:
    - name: whalesay
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [ cowsay ]
        args: [ "{{inputs.parameters.message}}" ]
