apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: example-workflow-4
spec:
  entrypoint: whalesay
  arguments:
    parameters:
      - name: message
        value: hello world
      - name: cmvalue
        valueFrom:
          configMapKeyRef:
            name: simple-parameters
            key: message
      - name: cm-example
        valueFrom:
          configMapKeyRef:
            key: message
            name: simple-parameters
      - name: job-name
        valueFrom:
          jsonPath: '{.metadata.name}'
      - name: job-obj
        valueFrom:
          jqFilter: '.'
      - name: previous_step_output
        valueFrom:
          path: /command_output/result.txt
  templates:
    - name: whalesays
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [ cowsay ]
        args: [ "{{inputs.parameters.message}}" ]
