apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-tester
  namespace: argo
  labels:
    example: 'true'
    clusterName: 'hubcluster'
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: whalesay
    templates:
      - name: whalesay
        container:
          image: alpine:3.6
          command: [sh, -c]
          args: ["date; sleep 5"]
