arguments:
  parameters:
    - name: deploy-to-dev-argocd-version
      value: v1.6.0
    - name: deploy-to-dev-application-name
      value: testapp-dev
    - name: deploy-to-dev-revision
      value: main
    - name: deploy-to-dev-flags
      value: --
    - name: argocd-server-address
      value: argocd-server.argocd.svc.cluster.local
