apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: normal-
spec:
  entrypoint: entry
  arguments:
    parameters:
      - name: argocd-server-address
        value: argocd-server.argocd.svc.cluster.local
      - name: argocd-credentials-secret
        value: argocd-user
  templates:
    - name: entry
      dag:
        tasks:
          - name: deploy-to-dev
            templateRef:
              name: argocd-step
              template: argocd-sync-and-wait
            arguments:
              parameters:
                - name: argocd-version
                  value: "{{workflow.parameters.deploy-to-dev-argocd-version}}"
                - name: application-name
                  value: "{{workflow.parameters.deploy-to-dev-application-name}}"
                - name: revision
                  value: "{{workflow.parameters.deploy-to-dev-revision}}"
                - name: flags
                  value: "{{workflow.parameters.deploy-to-dev-flags}}"
                - name: argocd-server-address
                  value: "{{workflow.parameters.argocd-server-address}}"
                - name: argocd-credentials-secret
                  value: "{{workflow.parameters.argocd-credentials-secret}}"
