arguments:
  parameters:
    - name: application-name-dev
      value: testapp-dev
    - name: revision
      value: main
    - name: argocd-server-address
      value: demoargocd.greenops.io
    - name: argocd-credentials-secret
      value: argocd-user
