arguments:
  parameters:
    - name: message
      value: hello world override
    - name: additional
      value: additional parameter
    - name: cmvalue
      valueFrom:
        configMapKeyRef:
          name: simple-parameters
          key: message
