metadata:
  Name: broken-workflow
  namespace: argo
  labels:
    example: 'true'
    clusterName: 'hubcluster'
spec:
  arguments:
    parameters:
      - name: message
        value: hello argo
  entrypoint: argosay
  templates:
    - name: argosay
      badinputparam: wrong
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      container:
        name: main
        image: 'argoproj/argosay:v2'
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
