metadata:
  generateName: broken
  namespace: argo
  labels:
    example: 'true'
    clusterName: 'hubcluster'
spec:
  arguments:
    parameters:
      - name: shouldnotbeoverriden
        value: should not be overriden
      - name: message
        value: hello argo
      - name: nil
        value: nil
      - name: cmvalue2
        valueFrom:
          configMapKeyRef:
            name: simple-parameters
            key: message
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      container:
        name: main
        image: 'argoproj/argosay:v2'
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
