arguments:
  parameters:
    - name: github-fetch-file-github-repo
      value: https://github.com/morzhanov/atlas-playground-private.git
    - name: github-fetch-file-path-to-file
      value: ghfile/github-fetch-file.yaml
    - name: github-fetch-file-github-credentials-secret
      value: github-pat
