arguments:
  parameters:
    - name: github-fetch-file-github-repo
      value: morzhanov/atlas-playground
    - name: github-fetch-file-path-to-file
      value: ghfile/github-fetch-file.yaml
    - name: github-fetch-file-github-credentials-secret
      value: github-pat
    - name: terraform-plan-config
      value: output-github-fetch-file/parameters/file-contents
