apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: terraform-plan
spec:
  templates:
    - name: terraform-plan
      inputs:
        parameters:
          - name: config
      outputs:
        parameters:
          - name: plan-result
            valueFrom:
              path: /tmp/plan_result.tf
      script:
        image: hashicorp/terraform
        command: [ bash ]
        source: |
          echo '{{inputs.parameters.config}}' > main.tf
          terraform plan -out=/tmp/plan_result.tf
