apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapp-staging
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/morzhanov/atlas-playground.git
    targetRevision: main
    path: deployment-manifest/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
