arguments:
  parameters:
    - name: application-name-dev
      value: testapp-dev
    - name: application-name-dev2
      value: testapp-dev2
    - name: application-name-stag
      value: testapp-staging
    - name: revision
      value: main
    - name: argocd-server-address
      value: test-argocd-server.argocd.svc.cluster.local
    - name: argocd-credentials-secret
      value: argocd-user
