apiVersion: v1
kind: ServiceAccount
metadata:
  name: wokrflow
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wokrflow
  namespace: argo
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wokrflow
subjects:
  - kind: ServiceAccount
    name: wokrflow
    namespace: argo
roleRef:
  kind: ClusterRole
  name: wokrflow
  apiGroup: rbac.authorization.k8s.io
