arguments:
  parameters:
    - name: message
      value: hello world override
    - name: additional
      value: additional parameter
    - name: additional9
      value: additional9 parameter
    - name: cmvalue
      valueFrom:
        configMapKeyRef:
          name: simple-parameters
          key: msg
    - name: cmvalue-2
      valueFrom:
        configMapKeyRef:
          name: simple-parameters
          key: message
    - name: cm-example
      valueFrom:
        configMapKeyRef:
          key: message
          name: simple-parameters
    - name: job-name
      valueFrom:
        jsonPath: '{.metadata.namespace}'
    - name: job-obj
      valueFrom:
        jqFilter: '._UPDATED'
    - name: previous_step_output
      valueFrom:
        path: /command_output/result_UPDATED.txt
