arguments:
  parameters:
    - name: message
      value: hello world override
    - name: additional
      value: additional parameter
    - name: cmvalue
      valueFrom:
        configMapKeyRef:
          name: simple-parameters
          key: msg
    - name: cmvalue-2
      valueFrom:
        configMapKeyRef:
          name: simple-parameters
          key: message
    - name: cm-example-2
      valueFrom:
        configMapKeyRef:
          key: message
          name: simple-parameters
    - name: job-name-2
      valueFrom:
        jsonPath: '{.metadata.name}'
    - name: job-obj-2
      valueFrom:
        jqFilter: '.'
    - name: previous_step_output-2
      valueFrom:
        path: /command_output/result.txt
