metadata:
  generateName: tester-
  namespace: argo
  labels:
    example: 'true'
    clusterName: 'hubcluster'
    argo-namespace: 'argo-2'
spec:
  arguments:
    parameters:
      - name: shouldnotbeoverriden
        value: should not be overriden
      - name: message
        value: hello argo
      - name: meta-example
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
  entrypoint: argosay
  templates:
    - name: argosay
      inputs:
        parameters:
          - name: message
            value: '{{workflow.parameters.message}}'
      container:
        name: main
        image: 'argoproj/argosay:v2'
        command:
          - /argosay
        args:
          - echo
          - '{{inputs.parameters.message}}'
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
