metadata:
  generateName: suspend-
  namespace: argo
  labels:
    clusterName: hubcluster
spec:
  entrypoint: suspend
  arguments:
    parameters:
      - name: message
        value: "Test message!"
  templates:
    - name: suspend
      steps:
        - - name: suspend
            templateRef:
              name: suspend
              template: suspend
            arguments:
              parameters:
                - name: message
                  value: "{{workflow.parameters.message}}"
