metadata:
  generateName: suspend-
  namespace: argo
  labels:
    clusterName: hubcluster
spec:
  entrypoint: suspend
  templates:
    - name: suspend
      steps:
        - - name: build
            template: whalesay
        - - name: delay
            template: delay

    - name: delay
      suspend:
        duration: "20"    # Must be a string. Default unit is seconds. Could also be a Duration, e.g.: "2m", "6h", "1d"

    - name: whalesay
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["hello world"]
