name: demo_pipeline
argo_version_lock: true
#cluster_name at the pipeline level means that every step in the pipeline will deploy to cluster_local.
#If cluster_name is also defined at a particular step, it will override the cluster_name set at the pipeline
#(only for that step).
cluster_name: in-cluster
steps:
- name: deploy_to_dev
  #This is the path of the ArgoCD Application file
  application_path: testapp_dev.yml
  rollback_limit: 1
  tests:
  - path: verifyendpoints.sh
    type: inject
    image: curlimages/curl:latest
    commands: [sh, -c, ./verifyendpoints.sh]
    before: false
    variables:
      SERVICE_INTERNAL_URL: testapp.dev.svc.cluster.local
