apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlastestapp-dev
  namespace: argocd
  annotations:
    atlas-argo-sync-prune: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/mihirpandya-greenops/atlas-playground.git
    targetRevision: main
    path: basic/argo_manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
