metadata:
  generateName: slack-send-message-
  namespace: argo
  labels:
    clusterName: hubcluster
spec:
  entrypoint: starter
  arguments:
    parameters:
      - name: webhook-url
        value: TODO_PROVIDE_WEBHOOKS_URL # example: https://hooks.slack.com/services/XXXXXXXXXXX/XXXXXXXXXXX
      - name: webhook-token
        value: TODO_PROVIDE_WEBHOOKS_TOKEN # example: XXXXXXXXXXXXXXXXXX
      - name: message
        value: "Test message!"
  templates:
    - name: starter
      steps:
        - - name: slack-send-message
            templateRef:
              name: slack-send-message
              template: slack-send-message
            arguments:
              parameters:
                - name: webhook-url
                  value: "{{workflow.parameters.webhook-url}}"
                - name: webhook-token
                  value: "{{workflow.parameters.webhook-token}}"
                - name: message
                  value: "{{workflow.parameters.message}}"
