metadata:
  generateName: argocd-testapp-
  namespace: argo
  labels:
    clusterName: hubcluster
spec:
  entrypoint: argocd-sync-and-wait
  arguments:
    parameters:
      - name: example
        value: example
      - name: application-name-dev
        value: testapp-dev
      - name: application-name-stag
        value: testapp-staging
      - name: revision
        value: main
      - name: argocd-server-address
        value: argo-cd-argocd-server.argocd.svc.cluster.local
      - name: argocd-credentials-secret
        value: argocd-user
  templates:
    - name: argocd-sync-and-wait
      steps:
        - - name: argocd-sync-and-wait
            templateRef:
              name: argocd-step
              template: argocd-sync-and-wait
            arguments:
              parameters:
                - name: application-name
                  value: "{{workflow.parameters.application-name-dev}}"
                - name: revision
                  value: "{{workflow.parameters.revision}}"
                - name: argocd-server-address
                  value: "{{workflow.parameters.argocd-server-address}}"
        - - name: argocd-sync-and-wait-2
            templateRef:
              name: argocd-step
              template: argocd-sync-and-wait
            arguments:
              parameters:
                - name: application-name
                  value: "{{workflow.parameters.application-name-dev}}"
                - name: revision
                  value: "{{workflow.parameters.revision}}"
                - name: argocd-server-address
                  value: "{{workflow.parameters.argocd-server-address}}"
