metadata:
  generateName: argocd-testapp-
  namespace: argo
  labels:
    clusterName: hubcluster
spec:
  entrypoint: starter
  arguments:
    parameters:
      - name: example
        value: example
  templates:
    - name: starter
      steps:
        - - name: deploy-to-dev
            templateRef:
              name: argocd-step
              template: argocd-sync-and-wait
            arguments:
              parameters:
                - name: application-name
                  value: "{{workflow.parameters.application-name-dev}}"
                - name: revision
                  value: "{{workflow.parameters.revision}}"
                - name: argocd-server-address
                  value: "{{workflow.parameters.argocd-server-address}}"
