arguments:
  parameters:
    - name: application-name-dev
      value: testapp-dev-malformed
    - name: revision
      value: main
    - name: argocd-server-address
      value: argocd-server.argocd.svc.cluster.local
    - name: argocd-credentials-secret
      value: argocd-user
