apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-tester
  namespace: argo
  labels:
    example: 'true'
    clusterName: 'hubcluster'
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    arguments:
      parameters:
        - name: message
          value: hello argo
    entrypoint: argosay
    templates:
      - name: argosay
        inputs:
          parameters:
            - name: message
              value: '{{workflow.parameters.message}}'
        container:
          name: main
          image: 'argoproj/argosay:v2'
          command:
            - /argosay
          args:
            - echo
            - '{{inputs.parameters.message}}'
    ttlStrategy:
      secondsAfterCompletion: 300
    podGC:
      strategy: OnPodCompletion
