apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: redis-delete-key
spec:
  templates:
    - name: redis-delete-key
      script:
        image: goodsmileduck/redis-cli
        command: [bash]
        source: |
          redis-cli -h localhost -p 6379 DEL {{inputs.parameters.key}}
      inputs:
        parameters:
          - name: key
            value: key
          - name: host
            value: redisserver.greenops.svc.cluster.local
          - name: port
            value: 6379
